apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  mysql_health_check.sh: |
    #!/bin/env bash
    mysql -h localhost -u root -p${MYSQL_ROOT_PASSWORD} -e "SELECT 1"
    
  init.sql: |
    CREATE DATABASE IF NOT EXISTS transactions;
    USE transactions;

    CREATE TABLE IF NOT EXISTS transactions (
        id INT AUTO_INCREMENT PRIMARY KEY,
        amount INT,
        description VARCHAR(255)
    );

    CREATE USER IF NOT EXISTS 'expense'@'%' IDENTIFIED BY 'ExpenseApp@1';
    GRANT ALL PRIVILEGES ON transactions.* TO 'expense'@'%';
    FLUSH PRIVILEGES;

    
    
   



