apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: RXhwZW5zZUFwcEAx       # ExpenseApp@1
  MYSQL_PASSWORD: RXhwZW5zZUFwcEAx            # ExpenseApp@1
