apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec: 
  replicas: 1
  selector:
    matchLabels:
      db: mysql
      tier: db
  strategy:
    type: Recreate 

  template: 
    metadata: 
      labels: 
        db: mysql
        tier: db
    spec: 
      volumes:
      - name: mysql-init-db
        configMap:
          name: mysql-initdb-config

      initContainers:
        - name: init-mysql
          image: mysql:8.0
          command: ["sh", "-c", "chmod +x /mnt/mysql_health_check.sh && /mnt/mysql_health_check.sh"]
          # command: ["sh", "-c", "mysql -h localhost -u root -p$MYSQL_ROOT_PASSWORD < /docker-entrypoint-initdb.d/init.sql"]
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_ROOT_PASSWORD 
          volumeMounts:
            - name: mysql-init-db
              mountPath: /docker-entrypoint-initdb.d

      containers:
        - name: mysql-cont
          image: mysql:8.0
          ports:
          - containerPort: 3306
            name: mysql 
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_ROOT_PASSWORD 
          volumeMounts:
            - name: mysql-init-db
              mountPath: /docker-entrypoint-initdb.d
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            exec:
              command: ["mysql", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD", "-e", "SELECT 1"]
            initialDelaySeconds: 10
            periodSeconds: 5

      
             
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    db: mysql
spec:
  type: ClusterIP
  #clusterIP: None # This means we are going to use Pod IP 
  selector:
    db: mysql
    tier: db
  ports:
  - name: mysqldb-port
    protocol: "TCP"
    port: 3306
    targetPort: 3306            
