apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-frontend
  labels:
    app: expense-frontend
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-frontend
      tier: frontend
  template:
    metadata:
      labels:
        app: expense-frontend
        tier: frontend
    spec:

      volumes:
      - name: expense-nginx-reverse-proxy
        configMap:
          name: expense-nginx-reverse-proxy

      initContainers:
      - name: check-nginx-ready
        image: busybox:1.31
        command: ['sh', '-c', 'echo -e "Checking for the availability of Nginx Server deployment"; while ! nc -z localhost 8o; do sleep 1; printf "-"; done; echo -e "  >> Nginx Server has been started";']

      containers:
      - name: expense-frontend-cont
        image: nginx:1.27.4
        ports:
        - name: expense-frontend
          containerPort: 80
        volumeMounts:
        - name: expense-nginx-reverse-proxy
          mountPath: /etc/nginx/conf.d/

---
apiVersion: v1
kind: Service
metadata:
  name: expense-frontend
  labels:
    app: expense-frontend
    tier: frontend
spec:
  type: NodePort
  selector:
    app: expense-frontend
    tier: frontend
  ports:
  - name: expense-frontend
    protocol: "TCP"
    port: 80
    targetPort: 80
    nodePort: 32127
