apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec: 
  replicas: 1
  selector:
    matchLabels:
      db: mysql
      tier: db
  strategy:
    type: Recreate 
  template: 
    metadata: 
      labels: 
        db: mysql
        tier: db
    spec: 
      containers:
        - name: mysql-cont
          image: mysql:8.0
          ports:
            - containerPort: 3306
              name: mysql 
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_ROOT_PASSWORD 
             
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    db: mysql
spec:
  type: ClusterIP
  #clusterIP: None # This means we are going to use Pod IP 
  selector:
    db: mysql
    tier: db
  ports:
  - name: mysqldb-port
    protocol: "TCP"
    port: 3306
    targetPort: 3306            
