# Base image
FROM tomcat:8.5

# ENV Variables
ENV DB_HOST     \
    DB_USERNAME \
    DB_PASSWORD \
    DB_PORT     \
    DB_NAME
    

# copy .war file to tomcat webapps/
COPY ./target/LoginWebApp.war /usr/local/tomcat/webapps/

WORKDIR /usr/local/tomcat/webapps/

CMD ["catalina.sh", "run"]
