FROM openjdk:8
EXPOSE 8080
COPY target/ProductManager-0.0.1-SNAPSHOT.jar product.jar
ENTRYPOINT ["java","-jar","/product.jar"]

# FROM openjdk:8-jdk-alpine
# WORKDIR /opt/app
# COPY target/wezvatech-demo-9739110917.jar app.jar
# ENTRYPOINT ["java","-jar","app.jar"]
