# Base image
FROM tomcat:8.5

# copy .war file to tomcat webapps/
COPY ./target/LoginWebApp.war /usr/local/tomcat/webapps/LoginWebApp.war

WORKDIR /usr/local/tomcat/webapps/
RUN rm -rf ROOT && mv LoginWebApp.war ROOT.war

CMD ["catalina.sh", "run"]

