# Here you need to write a module mysql_db to create a project specific database(transactions).
 # Here you need to write a module mysql_user to create a expense user that allows remote login(%).

  # Connect to MYSQL Server
  - name: connect to mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: localhost  # mysql.daws82s.online
    register: mysql_info
    ignore_errors: true

  # Print MYSQL Server Info
  - name: print the output
    ansible.builtin.debug:
      msg: "MySQL info: {{ mysql_info }}"

  # Setting Database, User and Password
  - name: Set Database User and Password
    ansible.builtin.set_fact:
      db: "{{ PROJECT_DEFAULT_DATABASE if PROJECT_DEFAULT_DATABASE is defined else SAMPLE_DATABASE }}"
      dbuser: "{{ PROJECT_DEFAULT_USER if PROJECT_DEFAULT_USER is defined else SAMPLE_USER}}"
      dbpwd: "{{ PROJECT_DEFAULT_USER_PASSWORD if PROJECT_DEFAULT_USER_PASSWORD is defined else SAMPLE_USER_PASSWORD }}"

  # Create project default database
  - name: Create project specific database
    mysql_db:
      name: "{{ db }}"
      state: present
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: localhost

  # Create project default user with remote login and with all the permissions on project default database
  - name: Create project specific user
    mysql_user:
      name: "{{ dbuser }}"
      state: present
      password: "{{ dbpwd }}"
      priv: "{{ db }}.*:ALL,GRANT"
      #priv: "transactions.*: ALL,GRANT"
      host: "{{ item }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: localhost
    loop:
        - '%'

  - name: Print database variables
    ansible.builtin.debug:
      msg: "db={{ db }}   dbuser={{ dbuser }} dbpwd={{ dbpwd }} "

[ec2-user@ip-172-31-8-74 tasks]$
[ec2-user@ip-172-31-8-74 tasks]$ cat create_project_specific_user_database.yml
# Here you need to write a module mysql_db to create a project specific database(transactions).
 # Here you need to write a module mysql_user to create a expense user that allows remote login(%).

  # Connect to MYSQL Server
  - name: connect to mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: localhost  # mysql.daws82s.online
    register: mysql_info
    ignore_errors: true

  # Print MYSQL Server Info
  - name: print the output
    ansible.builtin.debug:
      msg: "MySQL info: {{ mysql_info }}"

  # Setting Database, User and Password
  - name: Set Database User and Password
    ansible.builtin.set_fact:
      db: "{{ PROJECT_DEFAULT_DATABASE if PROJECT_DEFAULT_DATABASE is defined else SAMPLE_DATABASE }}"
      dbuser: "{{ PROJECT_DEFAULT_USER if PROJECT_DEFAULT_USER is defined else SAMPLE_USER}}"
      dbpwd: "{{ PROJECT_DEFAULT_USER_PASSWORD if PROJECT_DEFAULT_USER_PASSWORD is defined else SAMPLE_USER_PASSWORD }}"

  # Create project default database
  - name: Create project specific database
    mysql_db:
      name: "{{ db }}"
      state: present
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: localhost

  # Create project default user with remote login and with all the permissions on project default database
  - name: Create project specific user
    mysql_user:
      name: "{{ dbuser }}"
      state: present
      password: "{{ dbpwd }}"
      priv: "{{ db }}.*:ALL,GRANT"
      #priv: "transactions.*: ALL,GRANT"
      host: "{{ item }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: localhost
    loop:
        - '%'

  - name: Print database variables
    ansible.builtin.debug:
      msg: "db={{ db }}   dbuser={{ dbuser }} dbpwd={{ dbpwd }} "
